# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: nielski on Azure
author: Travis Nielsen
email: trn@nielski.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Travis Nielsen's technology blog. The opinions and views expressed in this blog are those of the author and do not necessarily state or reflect those of Microsoft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nielski.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: travisnielsen
github_username:  travisnielsen

markdown: kramdown

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-avatar
  - jekyll-seo-tag

remote_theme: jekyll/minima
show_excerpts: true

google_analytics: UA-69721722-1

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: mastodon,  user_url: "https://hachyderm.io/@travisnielsen" }
    - { platform: github,  user_url: "https://github.com/travisnielsen" }
    - { platform: twitter, user_url: "https://twitter.com/travisnielsen" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/travisnielsen/" }


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: 
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
